### ISSUE TITLE
Performance. 250ms to initialize

### ISSUE THREAD

**Issue by paulirish** [github-linker/chrome-extension#38]
On my macbook air, this extension pauses the load of the page for 250ms while it compiles and runs:

![image](https://cloud.githubusercontent.com/assets/39191/9287051/cb017522-42b8-11e5-8754-8597445d0ba4.png)

![image](https://cloud.githubusercontent.com/assets/39191/9287056/2e27031a-42b9-11e5-8fba-c6764da9e76b.png)

The upfront parsing is what really kills it. I am guessing because of the enormous JSON blob. 

To profile this i'm using about:tracing in chrome which gives you this level of detail.

**Comment by stefanbuck** [comment]
I'm thinking since a while about a bigger refactoring of the extension to get ride of the JSON file. My idea is to evaluate the package names on the fly without a lookup list or even just for the most popular packages. Unfortunately I'm busy with my new flat, but I will try to find a solution soon as possible.

**Comment by stefanbuck** [comment]
Just a quick status update on this. I'm currently working on a service, which will be soon responsible for the mapping. I'm very happy to get ride of these JSON files. Thanks for pushing me @paulirish  :wink: 

https://github.com/github-linker/live-resolver

**Comment by paulirish** [comment]
most good!​

**Comment by stefanbuck** [comment]
Fix in [v.3.8.0](https://github.com/github-linker/chrome-extension/releases/tag/v.3.8.0)
